Update out (#5)
* Update out

* update user check

update user check to check org

* fix

* fix

* tests

* test fix

* test fix

* fix

* Update out.sh

* Update out.sh

* Fix Tests

* Update out

* Update Tests

* Fix Tests

* Update deploy.yml

* Fix permissions

* update permissions

---------

Co-authored-by: Leonard Jones <leojones4902@gmail.com>

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -51,7 +51,71 @@ log_error() {
   log_message "ERROR" "$@"
 }
 
+# Function: check_org_membership
+#
+# Description: Checks if a user is a member of the specified github org by calling the Github Api
+#
+#
+# Returns 204 if BOTH requester and user is a member
+# Returns 302 if requester is not an org members
+# Returns 404 if requester and user is not a member
+declare -F check_org_membership >/dev/null || check_org_membership() {
+  set +e
+    response_with_headers=$(gh api \
+                -H "Accept: application/vnd.github+json" \
+                -H "X-GitHub-Api-Version: 2022-11-28" \
+                "/orgs/$org/members/$username" \
+                -i)
+    set -e
+  response_status_code=$(echo "$response_with_headers" | grep 'HTTP/' | awk '{print $2}')
+  log_debug "response_status_code: $response_status_code"
+  if [ "$response_status_code" -eq 204 ]; then
+      log_debug "Both Requestor and User are members of $org"
+      echo 0
+  elif [ "$response_status_code" -eq 302 ]; then
+      log_debug "Requestor is not a member of $org"
+      echo 1
+  elif [ "$response_status_code" -eq 404 ]; then
+      log_debug "User is not a member of  $org"
+      echo 1
+  else
+      log_error "Request failed with HTTP status code: $response_status_code."
+      echo 1
+  fi
+}
+check_if_valid_org_user() {
+  if [ -n "$ghe_host" ]; then
+    log_debug "ghe_host provided - using $ghe_host"
+    export GH_ENTERPRISE_TOKEN=$access_token
+    export GH_HOST=$ghe_host
+  else
+    log_debug "ghe_host not provided - using github.com"
+    export GH_TOKEN=$access_token
+  fi
+
+  log_info "Checking if $username belongs to $org"
+  result=$(check_org_membership)
+  log_info "result [$result]"
+
+  if [ "$result" -eq 0 ]; then
+    log_debug "$org is a valid org for $username"
+    echo 0
+  else
+    echo 1
+  fi
+
+}
+
 check_if_valid_user() {
+  if [ -n "$ghe_host" ]; then
+    log_debug "ghe_host provided - using $ghe_host"
+    export GH_ENTERPRISE_TOKEN=$access_token
+    export GH_HOST=$ghe_host
+  else
+    log_debug "ghe_host not provided - using github.com"
+    export GH_TOKEN=$access_token
+  fi
+
   if [ "$number_of_users" -gt 0 ]; then
     log_info "Checking [$number_of_users] users"
     for ((i = 0; i < number_of_users; i++)); do
@@ -59,8 +123,13 @@ check_if_valid_user() {
       log_debug "Checking user: $user"
       if [ "$user" == "$BUILD_CREATED_BY" ]; then
         log_debug "Found valid user: $user == $BUILD_CREATED_BY"
-        global_is_valid_user=1  # Early return if a match is found
-        return 0
+        log_info "Checking if $username belongs to $org"
+        result=$(check_if_valid_org_user)
+        log_debug "result [$result]"
+        if [ "$result" -eq 0 ]; then
+          global_is_valid_user=1  # Early return if a match is found
+          return 0
+        fi
       fi
     done
   fi
